source 'https://rubygems.org'

gem 'rspec', '~> 2.14.0'
gem 'capybara'
gem 'capybara-mechanize'
gem "capybara-webkit"
gem "selenium-webdriver"

gem 'pry'
gem 'pry-nav'
gem 'pry-doc'
gem 'pry-stack_explorer'